### ISSUE TITLE
torch-cluster 1.5.5 with pytorch 1.7.0+cu101

### ISSUE THREAD

**Issue by TheFloHub** [rusty1s/pytorch_cluster#92]
Hey,
I want to install torch-points3d which requires torch cluster 1.5.5 in an pytorch 1.7.0 environment.
I'm working on a windows 10 machine with Python 3.7.6 and pytorch 1.7.0+cu101.

When I try to install "pip install torch-cluster==1.5.5" I get the following error:

    ERROR: Command errored out with exit status 1:
     command: 'd:\virtualenv\points3dtorch\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Florian\\AppData\\Local\\Temp\\pip-install-c7catro5\\torch-cluster_2dfd8819f117438896fbd840290dd0f5\\setup.py'"'"'; __file__='"'"'C:\\Users\\Florian\\AppData\\Local\\Temp\\pip-install-c7catro5\\torch-cluster_2dfd8819f117438896fbd840290dd0f5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn'
         cwd: C:\Users\Florian\AppData\Local\Temp\pip-install-c7catro5\torch-cluster_2dfd8819f117438896fbd840290dd0f5\
    Complete output (40 lines):
    running egg_info
    creating C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info
    writing C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info\dependency_links.txt
    writing requirements to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info\requires.txt
    writing top-level names to C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info\top_level.txt
    writing manifest file 'C:\Users\Florian\AppData\Local\Temp\pip-pip-egg-info-wuvclnjn\torch_cluster.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Florian\AppData\Local\Temp\pip-install-c7catro5\torch-cluster_2dfd8819f117438896fbd840290dd0f5\setup.py", line 89, in <module>
        packages=find_packages(),
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "d:\python3.7.6\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python3.7.6\Lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\python3.7.6\Lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "d:\virtualenv\points3dtorch\lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "d:\python3.7.6\Lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "d:\python3.7.6\Lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "d:\python3.7.6\Lib\distutils\cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "d:\python3.7.6\Lib\distutils\dist.py", line 858, in get_command_obj
        cmd_obj = self.command_obj[command] = klass(self)
      File "d:\virtualenv\points3dtorch\lib\site-packages\torch\utils\cpp_extension.py", line 325, in __init__
        super().__init__(*args, **kwargs)
      File "d:\virtualenv\points3dtorch\lib\site-packages\torch\utils\cpp_extension.py", line 330, in __init__
        super(BuildExtension, self).__init__(*args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'no_python_abi_suffix'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can somebody help me out here? Is it even possible that 1.5.5 can be used with torch 1.7?

Thanks.

**Comment by rusty1s** [comment]
I'm pretty sure `torch-cluster=1.5.5` should work with PyTorch 1.7.0, but you can also install a more recent version. Those are compatible to each other.

The error suggests that `torch.utils.cpp_extension.BuildExtension` cannot handle the `no_python_abi_suffix`, which is weird to me. You can try to clone the repo from source and remove that argument from `setup.py`.
