### ISSUE TITLE
CMake compilation should use C++17 for PyTorch 2?

### ISSUE THREAD

**Issue by GericoVi** [rusty1s/pytorch_cluster#229]
Hi, I'm trying to compile the code on Windows using **MSVC 2019**. It seems that PyTorch 2 requires C++17 now, so if you want to build this repo for that using CMake I think line 3 in `CMakeLists.txt` should be changed from `set(CMAKE_CXX_STANDARD 14)` to `set(CMAKE_CXX_STANDARD 17)`. The former is fine when linking PyTorch 1.8.0 for example but doesn't work for PyTorch 2.2.2 for example unless C++17 is used.

Presumably, the compilation on the python side doesn't use the `CMakeLists.txt` and provides it's own compiler arguments to use C++17? But when compiling it manually this seems to come up.

**However**, leaving `set(CMAKE_CXX_STANDARD 17)` but trying to compile with PyTorch 1.8.0 does not seem to work. With many of the same error but an example snippet is:
```
C:\Users\utcgv3g21\Desktop\libtorch-win-shared-with-deps-1.8.0+cpu\libtorch\include\c10\util\C++17.h(303): error C2872: 'std': ambiguous symbol
C:\Users\utcgv3g21\Desktop\libtorch-win-shared-with-deps-1.8.0+cpu\libtorch\include\c10/util/variant.h(2796): note: could be 'std'
C:\Users\utcgv3g21\Desktop\libtorch-win-shared-with-deps-1.8.0+cpu\libtorch\include\c10/util/C++17.h(303): note: or       'std'
```

Note that the same thing is true when trying to compile on **MacOS with CMake** (like in [this example](https://github.com/pyg-team/pytorch_geometric/tree/master/examples/cpp)). In this case the error is pretty clear and suggests C++17:
```
[ 50%] Building CXX object CMakeFiles/hello-world.dir/main.cpp.o
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:4:2: error: C++17 or later compatible compiler is required to use ATen.
#error C++17 or later compatible compiler is required to use ATen.
 ^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:11:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:118:34: error: no template named 'variant' in namespace 'std'
  using warning_variant_t = std::variant<UserWarning, DeprecationWarning>;
                            ~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:121:7: error: unknown type name 'warning_variant_t'
      warning_variant_t type,
      ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:127:7: error: unknown type name 'warning_variant_t'
      warning_variant_t type,
      ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:133:7: error: unknown type name 'warning_variant_t'
      warning_variant_t type,
      ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:139:3: error: unknown type name 'warning_variant_t'
  warning_variant_t type() const;
  ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/Exception.h:146:3: error: unknown type name 'warning_variant_t'
  warning_variant_t type_;
  ^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:12:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/C++17.h:27:2: error: You need C++17 to compile PyTorch
#error You need C++17 to compile PyTorch
 ^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:13:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/intrusive_ptr.h:4:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:5:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/in_place.h:7:12: error: no member named 'in_place' in namespace 'std'
using std::in_place;
      ~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/in_place.h:8:12: error: no member named 'in_place_index_t' in namespace 'std'
using std::in_place_index_t;
      ~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/in_place.h:9:12: error: no member named 'in_place_t' in namespace 'std'
using std::in_place_t;
      ~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/in_place.h:10:12: error: no member named 'in_place_type_t' in namespace 'std'
using std::in_place_type_t;
      ~~~~~^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:13:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/intrusive_ptr.h:4:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:86:23: error: unknown type name 'in_place_t'
  explicit MaybeOwned(in_place_t, Args&&... args)
                      ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:178:27: error: unknown type name 'in_place_t'
  static MaybeOwned owned(in_place_t, Args&&... args) {
                          ^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:130:12: error: no template named 'is_nothrow_move_constructible_v' in namespace 'std'; did you mean 'is_nothrow_move_constructible'?
      std::is_nothrow_move_constructible_v<T>&&
      ~~~~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__type_traits/is_nothrow_move_constructible.h:27:29: note: 'is_nothrow_move_constructible' declared here
struct _LIBCPP_TEMPLATE_VIS is_nothrow_move_constructible
                            ^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:13:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/intrusive_ptr.h:4:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:130:46: error: expected '(' for function-style cast or type construction
      std::is_nothrow_move_constructible_v<T>&&
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:131:16: error: no template named 'is_nothrow_move_assignable_v' in namespace 'std'; did you mean 'is_nothrow_move_assignable'?
          std::is_nothrow_move_assignable_v<borrow_type>)
          ~~~~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__type_traits/is_nothrow_move_assignable.h:24:29: note: 'is_nothrow_move_assignable' declared here
struct _LIBCPP_TEMPLATE_VIS is_nothrow_move_assignable
                            ^
In file included from /Users/gericovidanes/Repos/torch_cpp_test/main.cpp:1:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/script.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/ATen.h:7:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/Context.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/ATen/core/Generator.h:13:
In file included from /Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/intrusive_ptr.h:4:
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:131:57: error: expected '(' for function-style cast or type construction
          std::is_nothrow_move_assignable_v<borrow_type>)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/gericovidanes/miniforge3/envs/pytorch2.2/lib/python3.11/site-packages/torch/include/c10/util/MaybeOwned.h:141:12: error: no template named 'is_nothrow_move_assignable_v' in namespace 'std'; did you mean 'is_nothrow_move_assignable'?
      std::is_nothrow_move_assignable_v<T>&& std::is_nothrow_move_assignable_v<
      ~~~~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__type_traits/is_nothrow_move_assignable.h:24:29: note: 'is_nothrow_move_assignable' declared here
struct _LIBCPP_TEMPLATE_VIS is_nothrow_move_assignable
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/hello-world.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
make: *** [all] Error 2
```

This is perhaps a PyTorch issue? But maybe a conditional in the `CMakeLists.txt` that uses either 14 or 17 depending on the libtorch version could work? Or just exposing this as a CMake variable?

Any thoughts on this?

**Comment by GericoVi** [comment]
Update, C++17 compilation actually does work when linking to PyTorch 1.13.1 for example. Unsure, which version is the breaking point, just adding this here for reference.

**Comment by nazarred** [comment]
I have the exact same problem when trying to build PyTorch Cluster (from the master branch) using PyTorch 2.7.1 and 2.6:

```
...
/opt/libtorch-2.6-cuda126/include/ATen/ops/instance_norm.h:27:122: error: ‘cudnn_enabled’ was not declared in this scope
   27 |     return at::_ops::instance_norm::call(input, weight, bias, running_mean, running_var, use_input_stats, momentum, eps, cudnn_enabled);
      |                                                                                                                          ^~~~~~~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/cross_entropy_loss.h:38:94: error: ‘label_smoothing’ was not declared in this scope
   38 |     return at::_ops::cross_entropy_loss::call(self, target, weight, reduction, ignore_index, label_smoothing);
      |                                                                                              ^~~~~~~~~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/convolution_overrideable.h:82:105: error: ‘transposed’ was not declared in this scope
   82 |     return at::_ops::convolution_overrideable_out::call(input, weight, bias, stride, padding, dilation, transposed, output_padding, groups, out);
      |                                                                                                         ^~~~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:47:127: error: ‘std::optional’ has not been declared
   47 |   static at::Tensor redispatch(c10::DispatchKeySet dispatchKeySet, int64_t window_length, bool periodic, double alpha, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
      |                                                                                                                               ^~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:47:135: error: expected ‘,’ or ‘...’ before ‘<’ token
   47 |   static at::Tensor redispatch(c10::DispatchKeySet dispatchKeySet, int64_t window_length, bool periodic, double alpha, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
      |                                                                                                                                       ^
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:51:68: error: ‘std::optional’ has not been declared
   51 |   using schema = at::Tensor (int64_t, bool, double, double, ::std::optional<at::ScalarType>, ::std::optional<at::Layout>, ::std::optional<at::Device>, ::std::optional<bool>);
      |                                                                    ^~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:51:76: error: expected ‘,’ or ‘...’ before ‘<’ token
   51 |   using schema = at::Tensor (int64_t, bool, double, double, ::std::optional<at::ScalarType>, ::std::optional<at::Layout>, ::std::optional<at::Device>, ::std::optional<bool>);
      |                                                                            ^
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:57:98: error: ‘std::optional’ has not been declared
   57 |   static at::Tensor call(int64_t window_length, bool periodic, double alpha, double beta, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
      |                                                                                                  ^~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:57:106: error: expected ‘,’ or ‘...’ before ‘<’ token
   57 |   static at::Tensor call(int64_t window_length, bool periodic, double alpha, double beta, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
      |                                                                                                          ^
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:58:140: error: ‘std::optional’ has not been declared
   58 |   static at::Tensor redispatch(c10::DispatchKeySet dispatchKeySet, int64_t window_length, bool periodic, double alpha, double beta, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
      |                                                                                                                                            ^~~~~~~~
/opt/libtorch-2.6-cuda126/include/ATen/ops/hamming_window_ops.h:58:148: error: expected ‘,’ or ‘...’ before ‘<’ token
   58 |   static at::Tensor redispatch(c10::DispatchKeySet dispatchKeySet, int64_t window_length, bool periodic, double alpha, double beta, ::std::optional<at::ScalarType> dtype, ::std::optional<at::Layout> layout, ::std::optional<at::Device> device, ::std::optional<bool> pin_memory);
...
```

Changing `set(CMAKE_CXX_STANDARD 14)` to `set(CMAKE_CXX_STANDARD 17)`  solved this problem for me (both on Linux and Windows):

![Image](https://github.com/user-attachments/assets/efb0c8e0-1ec0-402a-9be9-8233c5bf1637)


I opened a pull request with an updated `CMAKE_CXX_STANDARD` https://github.com/rusty1s/pytorch_cluster/pull/257 

If this is wrong for some reason, please say why.
